# Generated by Django 2.1.5 on 2020-04-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pp', models.ImageField(upload_to='pp/')),
            ],
        ),
    ]
