# Generated by Django 2.1.5 on 2020-04-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0005_game_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='gamer',
            name='games',
            field=models.ManyToManyField(blank=True, to='gamers.Game'),
        ),
        migrations.AddField(
            model_name='gamer',
            name='friends',
            field=models.ManyToManyField(blank=True, to='gamers.Friend'),
        ),
    ]
