# Generated by Django 2.1.5 on 2020-04-24 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0006_auto_20200422_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Gamer_ID',
            fields=[
                ('user', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=150)),
                ('seen', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_user', to='gamers.Gamer_ID')),
            ],
        ),
        migrations.AlterField(
            model_name='friend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_user', to='gamers.Gamer_ID'),
        ),
        migrations.AddField(
            model_name='friend_request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_request_user', to='gamers.Gamer_ID'),
        ),
        migrations.AddField(
            model_name='gamer',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, to='gamers.Friend_Request'),
        ),
        migrations.AddField(
            model_name='gamer',
            name='notifications',
            field=models.ManyToManyField(blank=True, to='gamers.Notification'),
        ),
    ]
