# Generated by Django 2.1.5 on 2020-04-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0007_auto_20200424_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='bio',
            field=models.CharField(default='', max_length=150),
        ),
    ]
