# Generated by Django 2.1.5 on 2020-04-24 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0008_auto_20200424_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend_Request_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=14)),
            ],
        ),
        migrations.AddField(
            model_name='friend_request',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='friend_request_status', to='gamers.Gamer_ID'),
        ),
    ]
