# Generated by Django 2.1.5 on 2020-04-24 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0010_auto_20200424_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='users',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='game_users', to='gamers.Gamer_ID'),
        ),
    ]
