# Generated by Django 2.1.5 on 2020-04-24 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0015_remove_game_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamer',
            name='games',
        ),
        migrations.AddField(
            model_name='game',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_users', to='gamers.Gamer_ID'),
        ),
    ]
